stages:
  - build
  - deploy

before_script:
  - echo "REACT_APP_RAPID_API_KEY=$CI_SECRET_API_KEY" > .env
  - npm install --legacy-peer-deps

build:
  stage: build
  script:
    - npm run build
  tags:
    - javascript

deploy:
  stage: deploy
  script:
    - netlify deploy --prod --dir=build --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN
  tags:
    - javascript
  only:
    - tags
