name: Deploy to Netlify

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Create .env file
        run: echo "REACT_APP_RAPID_API_KEY=${{ secrets.CI_SECRET_API_KEY }}" > .env
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Build project
        run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-folder
          path: build/

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://stay-fit-reactjs.netlify.app
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-folder
          path: build/
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Netlify CLI
        run: npm install netlify-cli -g
      - name: Deploy to Netlify
        run: netlify deploy --prod --dir=build --site=${{ secrets.NETLIFY_SITE_ID }} --auth=${{ secrets.NETLIFY_AUTH_TOKEN }}